import re
from typing import List, Optional, Literal
from pydantic import BaseModel, Field, field_validator
from app.services.ai.models import AIGeneratedField, SNAKE_CASE_PATTERN


class AIGeneratedRelationship(BaseModel):
    """Represents a visual cross-table relationship link generated by AI."""
    source_entity: str = Field(..., description="Source entity name containing the foreign key")
    source_field: str = Field(..., description="Foreign key column name in the source entity")
    target_entity: str = Field(..., description="Target entity name being referenced")
    target_field: str = Field(default="id", description="Primary key column name in the target entity")
    cardinality: Literal["1:1", "1:many", "many:many"] = "1:many"

    @field_validator("source_entity", "target_entity", "source_field", "target_field")
    @classmethod
    def clean_identifier(cls, v: str) -> str:
        clean = v.strip().lower().replace(" ", "_").replace("-", "_")
        clean = re.sub(r"[^a-z0-9_]", "", clean) or "id"
        return clean


class AIGeneratedProjectEntity(BaseModel):
    """An individual entity table in a generated multi-table project."""
    name: str = Field(..., min_length=1, max_length=100, description="Entity name in snake_case")
    description: Optional[str] = None
    fields: List[AIGeneratedField] = Field(..., min_length=1, description="List of columns for this table")

    @field_validator("name")
    @classmethod
    def validate_entity_name(cls, v: str) -> str:
        clean = v.strip().lower().replace(" ", "_").replace("-", "_")
        if not SNAKE_CASE_PATTERN.match(clean):
            clean = re.sub(r"[^a-z0-9_]", "", clean) or "entity"
        return clean


class AIGeneratedProject(BaseModel):
    """Complete multi-table schema draft generated for a domain."""
    project_name: str = Field(..., description="High-level title for the generated project")
    description: Optional[str] = None
    entities: List[AIGeneratedProjectEntity] = Field(..., min_length=1, max_length=12, description="Generated entity tables (capped at 4-10)")
    relationships: List[AIGeneratedRelationship] = Field(default_factory=list, description="Cross-entity relationship lines")
    validation_summary: Optional[dict] = Field(default=None, description="Pre-computed validation results from validation engine")
